### ISSUE TITLE
Consolidated Loan File - 26-12-2023 - Multiple Entries available

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#1114]

**Comment by Prakash3K** [comment]
Hi @TabrejAlam3K sir, can i create this ticket in support portal.


CC: @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Yes Mr. @Prakash3K

**Comment by Mahesh3ktech** [comment]
hi @TabrejAlam3K - 1) Which client upload the file contains 36399 records and it is taking more than 3 hours' time to upload the file and move to another FTP folder. 
2) In MS flow time interval set as 3 hours and every 3hours flow will look for the files which need to be uploaded if it is available then it processes to upload the file, now before completing upload of 36399 records file MS flow is looking for the file after 3 hours' time intervals, due to this duplicate is getting uploaded for the same file.

Solution: Need to set the time interval of 12 hours in MS flow. 


CC: @audhi3k @gsudarsan3k @Shasthara

**Comment by TabrejAlam3K** [comment]
I was trying to connect with the Client (Mr. Dikshant) - He is not available.

**Comment by TabrejAlam3K** [comment]
Solution - We have incresed the time interval from 3 hrs to 8 hrs.

@Prakash3K - Close this ticket from the support portal **total time effort = 2 Hrs**

CC : @audhi3k
