### ISSUE TITLE
MS Dynamics : Why 100+ emails suddenly come in my inbox-

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1150]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/f0ef1674-0c31-41f3-95ed-717e4a1036b2)

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K  and Mr @johnbosco3K update the status

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k - We have observed it was triggred form the UAT Environment, Currenlty we have stopped the UAT MS Flow.

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K - We can close this ticket from the support portal **without effort hours.**

CC : @audhi3k

**Comment by audhi3k** [comment]
Mr @TabrejAlam3K  why without hours

**Comment by TabrejAlam3K** [comment]
Hi Ms. @audhi3k Mam, We have not done anything for this, We have only hold the Ms flow.

**Comment by TabrejAlam3K** [comment]
Hi @Prakash3K - Close this ticket again with **2 Hrs time efforts**

Check with Ms. Audhi Mam and Mr. Shashtara on reclosure. We have spend 2 hrs on this for detail investigation.

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
After conducting a thorough investigation, we have discovered the following details. 
1.	According to the scheduler, the MS Flow was set to trigger and retrieve files from the LMS Folder, which contained a total of 30 files. However, during that time, the API was not functioning properly due to Microsoft Updates on the Staging sandbox. Although the API failure occurred, the email notification was still triggered 30 times.
2.	Additionally, the MS Flow attempted to delete the files from the FTPS Folder, but the FTP service was experiencing downtime. As a result, the MS Flow was unable to delete the corresponding records from the folder, and the email notifications were triggered 30 times.
To address this issue, we have disabled the MS Flow in the UAT Environment. If necessary, we will re-enable it at a later time.
