### ISSUE TITLE
List of IP address for Genworks

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#134]

**Comment by audhi3k** [comment]
@niranjand22, kindly update the Status

**Comment by niranjand22** [comment]
Since BC is hosted on the cloud we don't know the region.


[indiaregions.txt](https://github.com/3ktech/General/files/10836233/indiaregions.txt)


As of now We have shared IP addresses of the Indian Region. 

There are multiple sub-regions in the Indian region and we have shared all the IP addresses of the Indian region with the client.

**Comment by niranjand22** [comment]
IP address provided to them for

![Image](https://user-images.githubusercontent.com/116243958/222033816-dcb5799e-7c15-40b5-8fe7-25e3b1ab93dd.png)

 SouthIndia region

**Comment by niranjand22** [comment]
Theyhave white listed all south india ip addresses
