### ISSUE TITLE
TCS additional column needs to incorporate in Sales invoice report

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1527]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/3c4e2962-1823-4205-b623-05d2d1fbae49)

**Comment by TabrejAlam3K** [comment]
TCS additional column needs to incorporate in Sales invoice report (CAS-02287-S0Y6L9)
Requirement
    1. TCS Value should be display in the Sales Invoice Report.
    2. If TCS calculated over sales TCS line should be visible otherwise line should not be visible on Report layout.
    3. Line value caption should be "TCS ON SALES@0.10%".

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - You can take the reference of the below posted sales invoice in **UCPL_28032024**

**TST0035 ∙ Hindustan Unilever Ltd CSA C/o Srinivasa Logistics**

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @sruthi1017 - Please do the below changes and merge the code into the Master Branch, We need to deploy it by today.

1. TCS Row should be visible if TCS Amount calculated else row should not be visible.
2. Amount in Words should come based on the New Value, Currently it is coming based on Total Value.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
We got the closure confirmation from the client side.

![Image](https://github.com/3ktech/General/assets/116171982/c20aad9c-69db-464a-ab66-f2bd2e573bb0)

CC : @audhi3k
