### ISSUE TITLE
Support on the Functions

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#1528]

**Comment by Jayanth3KT** [comment]
![Image](https://github.com/3ktech/General/assets/142868335/1a4f4072-2246-4829-98ce-1a83466fcc6b)

**Comment by TabrejAlam3K** [comment]
Dear Tabrej,

Below are the points that we discussed the other day:

Approval Setup: We would want to implement the Approval mechanism for all the voucher types with the monetary limits in place, below is the matrix providing the details for the matrix:

<html>
<body>

Voucher Type | Limit | Maker | 1st & Final Approver | Remarks
-- | -- | -- | -- | --
All | Upto 5L | Sathish | Pooja |  
All | from 5,00,001 | Sathish | Dikshant/Rajesh/Sunil | Tabrej to comeback for Multiple Approvals for Single Document
All | Upto 5L | Pooja | No Approval |  
All | from 5,00,001 | Pooja | Dikshant/Rajesh/Sunil |  
All | Upto 5L | Dikshant/Rajesh/Sunil | No Approval |  
All | from 5,00,001 | Dikshant/Rajesh/Sunil | No Approval |  


</body>
</html>

The user mentioned above can be changed basis on the team size and the monetary limit would also be changed as decided in future. The setup should allow us to change them,


Restrictions on the User Activity:
 
Salaries & Stipend GL: The User should not be able to see Employee codes only specific to these GLs, including the Employee Ledger Entries. The purpose is that since the Salary & Stipend are confidential information, it should be restricted to selected users to view or modify this. Include any other ways in Dynamics that would allow other users to view these entries.
User should not be able to access the Analysis Views.
Below represents the level of restrictions we would want:
i.     The Level 1 of the Users should only be allowed to do entires through any voucher types and they will not have any view rights to the GLs meaning they can't View, Alter, Modify, Delete any posted GL entries
ii.     The Level 2 of users will have selective rights.
iii.     The Level 3 will have all the rights allowed in the Dynamics.


Please check the above and let us know if any other clarifications are needed.

**Comment by TabrejAlam3K** [comment]
I have sended mail to Mr. Dikshat for Effort Approval once he approved we will start working on it.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
as discussed with the client we need to hold this ticket till 11-07-2024 due to client is not available.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi the ticket it selft was on hold from client side. today we will discuss and close the ticket.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Due to non response we will close this tikcet by today EOD.

![Image](https://github.com/user-attachments/assets/481aa856-54fa-4dae-8300-4df2c914d498)

CC : @audhi3k @Shasthara

**Comment by TabrejAlam3K** [comment]
Please close the issue due to non response. already highlighted with the client.

![Image](https://github.com/user-attachments/assets/25f4acfc-0f39-4313-8202-dfe66b0f0c7c)

CC : @audhi3k
