### ISSUE TITLE
GAP Discussion with Technical

### ISSUE THREAD

**Issue by niranjand22** [3ktech/General#154]

**Comment by Ejaz3KT** [comment]
[GAP_GSTR 9,& GSTR 9 C.xlsx](https://github.com/3ktech/General/files/10928204/GAP_GSTR.9.GSTR.9.C.xlsx)

**Comment by Ejaz3KT** [comment]
@audhi3k I`ve updated the GAP document please review the document

**Comment by audhi3k** [comment]
[

[GAP_Fervid_BC_16-Mar-2023_V1.0.xlsx](https://github.com/3ktech/General/files/11038747/GAP_Fervid_BC_16-Mar-2023_V1.0.xlsx)

](url)

**Comment by audhi3k** [comment]
Enclosed the GAP (8 points GAP point):

1.5 Purchase Quote

2.1 Item Master => QR code and Bar Code

2.4 Shipment of Goods

2.5 Indent

3.4 PCD Posted Cheque Dated
3.There should be provisionn to maintain and handled post-dated checks.
4.There should be alert PDC, BG, EMD (Earnest Money Deposit)                                                                                    

3.9 Invoice is based on GRN => 5.There should be provision to view the invoice schedule against the orders so that the Invoice will be generated on time

3.12 Cheque Printing

3.18 Payment Terms
2.There should be provision to have multiple payment terms for the purchases as well as for the sales                      
Example:                                                                        
10% as Advance
50% on Delivery of Invoice
40% after 10 days of Invoice

**Comment by Ejaz3KT** [comment]
@audhi3k Madam I`ve created individual tickets for the remaining points

**Comment by audhi3k** [comment]
Closing this task, as each point is created seperately for tracking purposes
