### ISSUE TITLE
Multiple Payment for Purchase

### ISSUE THREAD

**Issue by audhi3k** [3ktech/General#187]

**Comment by niranjand22** [comment]
In india The above requirement can only be handled through customization

**Comment by niranjand22** [comment]
installment payment terms

**Comment by niranjand22** [comment]
analysis and des is done doc file has to be created

**Comment by Shasthara** [comment]
@niranjand22  to share the design document.

**Comment by niranjand22** [comment]
info given to ms Padma

**Comment by niranjand22** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



1 | Validation required on Each Installment   Line Can Not Have More than 100%
-- | --
2 | Validation Required on All installment combined together (total of %)can   not have more or less than 100%
3 | In Installmet Payment Terms Lines. It should be listed sequnce wise what   we enter  eg-Advance,On   Dispatch,Reciept,15 Days
4 | In Payment schedule due date should be editable for advance payment   lines.
5 | Any changes done to the value   should be reflected in Payment Schedule.
6 | Applies to Doc No is not getting auto updated in Journal Voucher because   of that adjustment entry is got getting posted and showing the error.
7 | In Journal Line Doc type is coming as payment , It should be blank.
8 | In Journal Line Due date should be updated based on the Dates.
9 | In Purchase order Post Advance is not working.



</body>

</html>

**Comment by Padma2717** [comment]
@niranjand22 

cc: @audhi3k 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Dell/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Dell/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">

<div ccp_infra_version=3 ccp_infra_timestamp=1681983433397 ccp_infra_user_hash=3455855032
ccp_infra_copy_id="" data-ccp-timestamp=1681983433397>



Sl No. | Multiple Payment   terms points | Pages | Technical   Status |  
-- | -- | -- | -- | --
1 | Validation required   on Each Installment Line Can Not Have More than 100% | Installment Payment Terms | Done |  
2 | Validation Required   on All installment combined together (total of %)can not have more or less   than 100% | Installment Payment Terms | Done |  
3 | In Installmet Payment   Terms Lines. It should be listed sequnce wise what we enter  eg-Advance,On Dispatch,Reciept,15 Days | Installment Payment Terms | Pending |  
4 | In Payment schedule   due date should be editable for advance payment lines. | Payment Scheduled | Done |  
5 | Any changes done to   the value should be reflected in Payment Schedule. | Payment Scheduled | Done | ( added for amount,GST Related fields)
6 | Applies to Doc No is   not getting auto updated in Journal Voucher because of that adjustment entry   is got getting posted and showing the error. | Post Payment Schedule | Waiting for   fucntional response | Amount must be negative in Gen.   Journal Line Journal Template Name='JOURNALV',Journal Batch   Name='INSTALL',Line No.='40000'.
7 | In Journal Line Doc   type is coming as payment , It should be blank. | Post Payment Schedule | Done |  
8 | In Journal Line Due   date should be updated based on the Due Dates from the Payment Schedule | Post Payment Schedule | Done |  
9 | In Purchase order   Post Advance is not working. | Purchase Order | Pending |  



</body>

</html>

**Comment by Padma2717** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Dell/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Dell/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

<div ccp_infra_version=3 ccp_infra_timestamp=1682088512480 ccp_infra_user_hash=3455855032
ccp_infra_copy_id=266d06b1-4b46-453e-86eb-d562f8f37a76 data-ccp-timestamp=1682088512480>



Sl No. | Multiple   Payment terms points | Pages | Technical Status
-- | -- | -- | --
1 | Validation required   on Each Installment Line Can Not Have More than 100% | Installment Payment Terms | Done
2 | Validation Required   on All installment combined together (total of %)can not have more or less   than 100% | Installment Payment Terms | Done
3 | In Installmet Payment   Terms Lines. It should be listed sequnce wise what we enter  eg-Advance,On Dispatch,Reciept,15 Days | Installment Payment Terms | Pending
4 | In Payment schedule   due date should be editable for advance payment lines. | Payment Scheduled | Done
5 | Any changes done to   the value should be reflected in Payment Schedule. | Payment Scheduled | Done
6 | Applies to Doc No is   not getting auto updated in Journal Voucher because of that adjustment entry   is got getting posted and showing the error. | Post Payment Schedule | Done
7 | In Journal Line Doc   type is coming as payment , It should be blank. | Post Payment Schedule | Done
8 | In Journal Line Due   date should be updated based on the Due Dates from the Payment Schedule | Post Payment Schedule | Done
9 | In Purchase order   Post Advance is not working. | Purchase Order | Done
10 | Before Purchase post validation   should add for Advance Post | Purchase Order | Done
11 | Journal Due date   field map from Payment Schedule Due Date | Process | done



</body>

</html>

**Comment by niranjand22** [comment]
Let me know once pending point is also done

**Comment by audhi3k** [comment]
Internal Testing and UAT with the client to be done today

**Comment by Padma2717** [comment]
Pending point also done.

**Comment by niranjand22** [comment]
client apporved the customization.
