### ISSUE TITLE
Sales Invoice alignment

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#21]
There are following alignment changes in the Sales Invoice Report:

Address- Need to cross check its combined or not
Two Email ID need to print
A) In Company info - New field need to create "Email Id for Sales Invoice"
B) Job No(Sales header) >>Project manager>>Resource card-Email Id
Font size and style same - Kaliber 15size(cero)
Need to check field mapping for Ref No.
Need to add additional field "Ref No" In sales header-100 text length (This will flow to posted sales invoice header)
Project controller should be in same line as project manager
GSTIN need to align
IFSC code /SAC code Fichtner team will update
Header and Footer- Fichtner team will revert back
Domestic Sales- Fichtner team will revert back
Being Invoice- Fichtner team will revert back
[https://3ktechnologies22.sharepoint.com/🅱️/s/Fichtner/ETcov29mzftIr07vNX3gM6cBsAmHwa15Qv-RvBkpsuIXsQ?e=U9bD7o](https://github.com/users/3ktech/projects/17/views/url)

**Comment by audhi3k** [comment]
@Amar-3KT , kindly co-ordinate with client on UAT

**Comment by Amar-3KT** [comment]
There are following changes required:


1) The Invoice should be aligned (all the details to be moved down) to fit in our letter head format
2) The total width of the invoice can be reduced, leaving more space in both the sides
3) Font size of all the details in the invoice can be reduced by a number
4) In “Ref :” box please remove the “Service Order No.” text and also the “dt.23/12/2022”. Instead of the two bifurcation for Order No. and date, please make it as one and leave it blank so that it will enable us to type the required details in the required format
5) In the place where the “Domestic Sales” is appearing we would require to type Job descriptions, that is we require 2 or three lines of space above the invoice descriptions, therefore while we are preparing the invoice there should be a provision to key in the description, the same can also be a provision provided in Job card so that the same will repeat when we prepare invoice under the same job. However the slot should be editable incase there is a requirement to change while we prepare an invoice.
6) Post the job description, we will require to feed invoice descriptions which will be appearing in the places of Domestic sales and Manday charges. It is dynamic and needs to be a blank space which have to be filled every time invoice is being prepared.
7) There should be a sub-total appearing for highlighting the total invoice value above the GST amounts.
8) In the sample attached payable value in words is wrong, kindly correct the same.
9) In many invoices we would require numbers to be presented in an inner column in addition to numbers appearing in the INR column, please see if a text box kind can be inserted to enter amounts in addition to the usual INR column.
10) 1st signature place shall have the below options to be chosen from like a drop down list,
Project Manager
Executive Director – Corporate BDT
General Manager – Corporate BDT
Director
2nd signature place shall have “Project Controller”

**Comment by audhi3k** [comment]
@sandhya3k, update the comments on the GIT

**Comment by audhi3k** [comment]
@Amar-3KT, kindly do the testing on the report and update the status

**Comment by sandhya3k** [comment]
@Amar-3KT please test the sales invoice report as per client request.

**Comment by Amar-3KT** [comment]
1) Fichtner logo and address should align to right side as per format
2) Header address need to pic from location
3) Instead of man day charges Please provide 1 txt field in sales header
4) Please remove "domestic sales" Invoice/Description already we picked 
5) Signature- Project Controller change to Project Manager and 2nd signature write Project Controller (C Caps)
6) Please check amount after point.    i.g- Zero paisa only

**Comment by sandhya3k** [comment]
@Amar-3KT can u Please test the report?

**Comment by Amar-3KT** [comment]
1)Please check -Invoice/Description
2) check Layout
3) check amount, sub total  not showing
4) Reduce box size and align address right side 
5) Space required between City and post code in header 
@sandhya3k

**Comment by audhi3k** [comment]
Amarjeet has completed the testing and UAT to be done

**Comment by Amar-3KT** [comment]
Waiting for Client confirmation

**Comment by audhi3k** [comment]
@Amar-3KT , send mail to Mr Singaravel for closure of the ticket

**Comment by Amar-3KT** [comment]
@Ejaz3KT 
Need to Remove GSTIN and Dash(Pincode-) from report- In case of blank fields.

**Comment by niranjand22** [comment]
completed
