### ISSUE TITLE
Ship to contact not updating in customer ledger

### ISSUE THREAD

**Issue by Shasthara** [3ktech/General#319]

**Comment by TabrejAlam3K** [comment]
Clients Comments

Values for “Ship to contact” in Customer Ledger (Page ID 25) and Table ID 21 are not flown from 1.4.23 and it is coming blank. In our analysis, we find this is due to the “Field Length” issue consequent on the creation of a new field name. Earlier “Ship to contact” is flown from Page ID 50015. This has been now changed to Table ID 18. Values have been updated up to 31.3.23 while values are not flown from new Table ID 18 from 1.4.23. Please do the needful immediately and also provide us the details of the new field names introduced and corresponding Reports/Page ID/Table ID to check whether they have been mapped and reflected in respective reports.

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - In Customer Ledger Entries some entries having blank value in **Ship-to Contact**, Can you please check whether the custom filed is mapped properly for data populating.


CC : CC : @audhi3k @narayana3kt @Shasthara

**Comment by TabrejAlam3K** [comment]
@sandhya3k - As per our discussion please update your comment once it will get completed.

**Comment by TabrejAlam3K** [comment]
Ms. Sandhya is working on she will update once it will get completed.

**Comment by panduc** [comment]
@TabrejAlam3K the issue has been fixed and deployed in UAT. Please check and confirm.

Tested document: LKS01-2223-02416

CC : @audhi3k @narayana3kt @Shasthara

**Comment by TabrejAlam3K** [comment]
Hi Mr. @panduc - I have tested it in UAT Environment. It is working as per the expectation. Please move this changes in to the Production.

![Image](https://user-images.githubusercontent.com/116171982/235073956-fb477b93-618a-4926-8d3b-9e30b075eb1e.png)

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Confirmed by the client on 17-05-2023 as completed.

CC : @audhi3k @Shasthara
