### ISSUE TITLE
RTB accepted by Navision Business Central with inconsistent data

### ISSUE THREAD

**Issue by TabrejAlam3K** [3ktech/General#680]
Dear Tabrej,

Please refer to the above-mentioned RTB No.0000877793 received in Navision BC.  This RTB is created for client code 11261  JUBILANT AGRI & CONSUMER PRODUCTS LIMITED.   The relevant case ID referred to in the RTB is 5046161.

According to this case ID, the office code for this RTB is 31877.  However, the RTB is pushed to Navision Business Central with office Code 31878. We could find this because the GSTIN number is not available and we tried verifying the location of the client.  Otherwise, the Billing user would have posted the Invoice.

Is Navision Business Central not validating at the time of receiving the RTB request and rejecting that incorrect/inconsistent RTB?  Please verify, review, and provide your comments.

**Comment by TabrejAlam3K** [comment]
Response Snapshot Received from Mr. Somendra.

![Image](https://github.com/3ktech/General/assets/116171982/419b6df2-bb65-4fcd-9709-fdeb7d08ee48)

CC : @audhi3k @3ktech

**Comment by audhi3k** [comment]
Mr Karthik @3ktech  and Mr @TabrejAlam3K  can we connect on this tomorrow at 10:30

**Comment by TabrejAlam3K** [comment]
Hi @audhi3k - Will connect on this to investigate the issues.

**Comment by 3ktech** [comment]
hi @TabrejAlam3K , the RTB was received and created successfully in BC and then it was deleted by someone. The RTB was received once again and system has accepted since there was no Open Sales Invoice or Posted Sales Invoice for this RTB. Since there was no log enabled for Sales Document in change log, we are not able to troubleshoot how was the document deleted.
Cc: @Shasthara @Jayanth3KT
