### ISSUE TITLE
TP event force integration

### ISSUE THREAD

**Issue by Jayanth3KT** [3ktech/General#917]

**Comment by Mahesh3ktech** [comment]
Created the Sales Header and Sales Line tables and pages and created codeunit.

Working on process sales invoice.

**Comment by Tushargupta3K** [comment]
Few more points Requested by the TP team during UAT sessions:-
1.  In intial dicussion it was decided to have single G/L account 510200, now they have stated to have it like below :- if Business code = TTCP - G/L account =510500 otherwise G/L account 510200
2.  Event line description needs to be added like
3. Need to add 1 more dimension called - Product code Mapping:- Eventsforce.Eventproperties.Businessunit 
4. Exclude the Event line creation in sales invoice which have amount =0

**Comment by Mahesh3ktech** [comment]
hi @Tushargupta3K - all the 4 points are completed in Prod copy, kindly test and confirm ill move the changes to TpProduction1.

CC: @audhi3k @gsudarsan3k

**Comment by TabrejAlam3K** [comment]
Hi @Mahesh3ktech - what is the update on this.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
Hi @Mahesh3ktech - As discussed, this is resolved earlier and their are no support case for this. We are closing this ticket as completed.

CC : @audhi3k
