### ISSUE TITLE
Field Length issue on Check No. field

### ISSUE THREAD

**Issue by 3ktech** [3ktech/General#94]

**Comment by 3ktech** [comment]
hi @panduc , guide @Mahesh3ktech  on how to handle this issue. @Mahesh3ktech , discuss with @panduc about the same.

**Comment by 3ktech** [comment]
To be clarified with @audhi3k on some points to close this ticket.

**Comment by Mahesh3ktech** [comment]
Development completed and deployed in UAT.

Modified Objects are:
Table Extension: 50061, 50062, and 50088.
Page Extension: 50068, 50069, 50070, 50072, and 50073.
Report: 50013, 50014, 50017, 50021, 50035, 50114, 50131, and 50183.
Codeunit: 50007.

@niranjand22 you can do the testing in UAT server.

**Comment by niranjand22** [comment]
Currently, BC UAT server is not getting opened. will do testing once it opens.

**Comment by panduc** [comment]
@niranjand22 I'm able to access. Please make sure you are accessing the right URL? share us the screenshot of the issue.

**Comment by audhi3k** [comment]
@niranjand22, complete the testing and update the comment

**Comment by niranjand22** [comment]
@Mahesh3ktech 

Tested in UAT. cheque no. (35 char) value is populating properly in the Bank receipt voucher and cust, bank and GL entries.

there is one point which needs to be changed.

1. While posting the Bank receipt voucher it is asking to fill  the cheque no (10) char field. Instead of that it should validate with cheque no (35 char) field.

**Comment by niranjand22** [comment]
It is working fine now. TESTED in UAT
