### ISSUE TITLE
Transfer recipt issue for Subcon barcode

### ISSUE THREAD

**Issue by Prakash3K** [3ktech/General#947]

**Comment by Prakash3K** [comment]
@TabrejAlam3K 




![Image](https://github.com/3ktech/General/assets/140147250/f1838a35-06d3-4d6b-bee9-a0563463e0b5)

**Comment by TabrejAlam3K** [comment]
As per our screen sharing session he will post and let us know.

CC : @audhi3k

**Comment by TabrejAlam3K** [comment]
As per our last session with the Client Mr. Rewat said he will post the transaction at their end and let us know. Closing this ticket as completed because they have not yet highlighted again.

Mr. @Prakash3K - You can close this ticket form the Support portal with **Effort Hours = 6 Hours**

CC : @audhi3k @Sarikab1222
